### ISSUE TITLE
Documentation not buildable

### ISSUE THREAD

**Issue by quanah** [cyrusimap/cyrus-sasl#706]
It is currently not possible to build the cyrus-sasl documentation for the 2.1.28 release:

```
 more /tmp/sphinx-err-099bk_9r.log
# Sphinx version: 1.8.5
# Python version: 3.8.10 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.10.1
# Last messages:
#   reading sources... [ 98%] sasl/windows
#   reading sources... [ 99%] setup
#   reading sources... [100%] support
#
#   looking for now-outdated files...
#   none found
#   pickling environment...
#   done
#   checking consistency...
#   done
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.5) from /usr/lib/python3/dist-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.8) from /usr/lib/python3/dist-packages/alabaster/__init__.py
#   sphinx.ext.coverage (1.8.5) from /usr/lib/python3/dist-packages/sphinx/ext/coverage.py
#   sphinx.ext.extlinks (1.8.5) from /usr/lib/python3/dist-packages/sphinx/ext/extlinks.py
#   sphinx.ext.graphviz (1.8.5) from /usr/lib/python3/dist-packages/sphinx/ext/graphviz.py
#   sphinx.ext.ifconfig (1.8.5) from /usr/lib/python3/dist-packages/sphinx/ext/ifconfig.py
#   sphinx.ext.todo (1.8.5) from /usr/lib/python3/dist-packages/sphinx/ext/todo.py
#   sphinx.ext.intersphinx (1.8.5) from /usr/lib/python3/dist-packages/sphinx/ext/intersphinx.py
#   sphinxlocal.builders.manpage (0.1) from /home/build/git/cyrus-sasl/docsrc/exts/sphinxlocal/builders/manpage.py
#   sphinxlocal.roles.saslman (unknown version) from /home/build/git/cyrus-sasl/docsrc/exts/sphinxlocal/roles/saslman.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 342, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 412, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/build/git/cyrus-sasl/docsrc/exts/sphinxlocal/builders/manpage.py", line 86, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3/dist-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/home/build/git/cyrus-sasl/docsrc/exts/sphinxlocal/writers/manpage.py", line 37, in translate
    visitor = CyrusManualPageTranslator(self.document, self.builder)
  File "/home/build/git/cyrus-sasl/docsrc/exts/sphinxlocal/writers/manpage.py", line 49, in __init__
    BaseTranslator.__init__(self, document, builder, *args, **kwds)
  File "/usr/lib/python3/dist-packages/sphinx/writers/manpage.py", line 89, in __init__
    BaseTranslator.__init__(self, *args, **kwds)
  File "/usr/lib/python3/dist-packages/docutils/writers/manpage.py", line 171, in __init__
    self.settings = settings = document.settings
AttributeError: 'CyrusManualPageBuilder' object has no attribute 'settings'
```

**Comment by quanah** [comment]
Ok, due to the version of Sphinx shipped with Ubuntu 20.04 LTS not being compatible with the current doc settings, requires upgrade to Sphinx 4.x
